model:
  lr: 0.0003
  weight_decay: 0.0001
  hidden_size: 128
  num_layers: 10
  num_heads: 4
  ff_mult: 3
  mask_prob: 0.2
  dropout: 0.2
  label_smoothing: 0.0
  num_mem_kv: 32
  num_warmup_epochs: 30
  f_patchmerger: False
run:
  seed: 1337
  max_epochs: 750
dataset:
  dir: "./datasets/compare22-VOC-C"
  sr: 16000
